PUT http://localhost:8080/events/4
content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyMkB0ZXN0LmNvbSIsImV4cCI6MTcyMDAxNjQ1NCwidXNlcklkIjoyfQ.OreYqp5CbgdLewHmCBCVYU_oWEt6WIGEhKQEHxFKzaY

{
    "name": "Arshaluys1111",
    "description":"test desc updates 4444",
    "location": "test locaion updates",
    "dateTime": "2024-01-01T15:20:30.111Z" 
}
